require "rails_helper"

RSpec.describe GithubUserReposLister do
  describe ".call" do
    let(:owner) { "rails" }
    let(:repos) do
      [
        { name: "account_location", stars: 72 },
        { name: "actioncable", stars: 1091 },
        { name: "actioncable-examples", stars: 651 },
        { name: "actionmailbox", stars: 125 },
        { name: "actionpack-action_caching", stars: 259 },
        { name: "actionpack-page_caching", stars: 340 },
        { name: "actionpack-xml_parser", stars: 48 },
        { name: "actiontext", stars: 404 },
        { name: "activejob", stars: 748 },
        { name: "activemodel-globalid", stars: 90 },
        { name: "activemodel-serializers-xml", stars: 50 },
        { name: "activerecord-deprecated_finders", stars: 67 },
        { name: "activerecord-session_store", stars: 491 },
        { name: "activeresource", stars: 1260 },
        { name: "activestorage", stars: 737 },
        { name: "activesupport-json_encoder", stars: 48 },
        { name: "acts_as_list", stars: 385 },
        { name: "acts_as_nested_set", stars: 71 },
        { name: "acts_as_tree", stars: 278 },
        { name: "arel", stars: 2071 },
        { name: "asset_server", stars: 26 },
        { name: "atom_feed_helper", stars: 38 },
        { name: "auto_complete", stars: 212 },
        { name: "buildkite-config", stars: 15 },
        { name: "cache_digests", stars: 643 },
        { name: "coffee-rails", stars: 232 },
        { name: "commands", stars: 339 },
        { name: "conductor", stars: 54 },
        { name: "continuous_builder", stars: 7 },
        { name: "country_select", stars: 178 },
        { name: "cssbundling-rails", stars: 468 },
        { name: "dartsass-rails", stars: 162 },
        { name: "deadlock_retry", stars: 26 },
        { name: "discourse-rubyonrails-theme", stars: 6 },
        { name: "docked", stars: 1193 },
        { name: "dynamic_form", stars: 194 },
        { name: "esbuild-rails", stars: 148 },
        { name: "etagger", stars: 40 },
        { name: "exception_notification", stars: 850 },
        { name: "execjs", stars: 461 },
        { name: "fcgi_handler", stars: 2 },
        { name: "gem-buildkite-config", stars: 3 },
        { name: "globalid", stars: 1081 },
        { name: "gsoc2013", stars: 31 },
        { name: "gsoc2014", stars: 37 },
        { name: "hide_action", stars: 4 },
        { name: "homepage", stars: 49 },
        { name: "homepage-2011", stars: 27 },
        { name: "http_authentication", stars: 22 },
        { name: "importmap-rails", stars: 866 },
        { name: "in_place_editing", stars: 230 },
        { name: "irs_process_scripts", stars: 22 },
        { name: "iso-3166-country-select", stars: 70 },
        { name: "javascript_test", stars: 19 },
        { name: "jbuilder", stars: 4221 },
        { name: "journey", stars: 223 },
        { name: "jquery-rails", stars: 939 },
        { name: "jquery-ujs", stars: 2613 },
        { name: "jsbundling-rails", stars: 677 },
        { name: "kredis", stars: 1250 },
        { name: "localization", stars: 12 },
        { name: "marcel", stars: 358 },
        { name: "open_id_authentication", stars: 285 },
        { name: "pjax_rails", stars: 676 },
        { name: "propshaft", stars: 616 },
        { name: "protected_attributes", stars: 228 },
        { name: "prototype-rails", stars: 55 },
        { name: "prototype-ujs", stars: 63 },
        { name: "prototype_legacy_helper", stars: 60 },
        { name: "rails", stars: 52859 },
        { name: "rails-bot", stars: 13 },
        { name: "rails-contributors", stars: 132 },
        { name: "rails-controller-testing", stars: 285 },
        { name: "rails-deprecated_sanitizer", stars: 8 },
        { name: "rails-dev-box", stars: 2047 },
        { name: "rails-docs-server", stars: 25 },
        { name: "rails-dom-testing", stars: 136 },
        { name: "rails-html-sanitizer", stars: 272 },
        { name: "rails-master-hook", stars: 5 },
        { name: "rails-observers", stars: 503 },
        { name: "rails-perftest", stars: 764 },
        { name: "rails-probot", stars: 9 },
        { name: "rails-ujs", stars: 15 },
        { name: "rails_fast_attributes", stars: 19 },
        { name: "rails_upgrade", stars: 439 },
        { name: "rails_xss", stars: 106 },
        { name: "record_tag_helper", stars: 46 },
        { name: "render_component", stars: 39 },
        { name: "request.js", stars: 305 },
        { name: "requestjs-rails", stars: 76 },
        { name: "request_profiler", stars: 17 },
        { name: "rollupjs-rails", stars: 48 },
        { name: "routing_concerns", stars: 155 },
        { name: "ruby-coffee-script", stars: 26 },
        { name: "sass-rails", stars: 852 },
        { name: "scaffolding", stars: 17 },
        { name: "scriptaculous_slider", stars: 18 },
        { name: "sdoc", stars: 805 },
        { name: "spring", stars: 2758 },
        { name: "spring-watcher-listen", stars: 63 },
        { name: "sprockets", stars: 890 },
        { name: "sprockets-rails", stars: 558 },
        { name: "sqlite2_adapter", stars: 3 },
        { name: "ssl_requirement", stars: 318 },
        { name: "strong_parameters", stars: 1282 },
        { name: "tailwindcss-rails", stars: 1181 },
        { name: "thor", stars: 4983 },
        { name: "token_generator", stars: 25 },
        { name: "tzinfo_timezone", stars: 13 },
        { name: "tztime", stars: 8 },
        { name: "upload_progress", stars: 39 },
        { name: "verification", stars: 59 },
        { name: "web-console", stars: 1340 },
        { name: "weblog", stars: 65 },
        { name: "webpacker", stars: 5323 },
        { name: "website", stars: 34 },
      ]
    end

    it "counts how many stars a repository has" do
      VCR.use_cassette("rails_org_on_gh") do
        expect(described_class.call(owner)).to eq(repos)
      end
    end
  end
end
